### ISSUE TITLE
project dependencies

### ISSUE THREAD

**Issue by justinmk** [nebula-plugins/gradle-resolution-rules-plugin#10]
I've spent a few minutes with the plugin, and it seems to work for typical maven-style dependencies. For example, the `com.acme:foo` dependency is denied (as intended) with this configuration:

```json
  "deny": [
    {
      "module": "com.acme:foo",
      "reason" : "sibling dependency",
    }
  ],
```

```groovy
dependencies {
  resolutionRules files('resolution-rules.json')
  compile 'com.acme:foo'
}
```

But it does not deny the dependency if it is declared with `project()`, like this:

```groovy
dependencies {
  resolutionRules files('resolution-rules.json')
  compile project(':foo')
}
```

Is this support, or planned? Thanks.

**Comment by rspieldenner** [comment]
Project dependencies are treated specially in gradle. We'd have to do some extra checks.

I'd suggest starting a different plugin to prevent sibling dependencies in a multiproject, since the usual point of having a multiproject is that some of the siblings depend on the others.

**Comment by justinmk** [comment]
@rspieldenner Thanks for the pointers. So it's not a goal of this plugin, I'll close this then.
