### ISSUE TITLE
Support version patterns for determining which part of the version to align against and compare

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-resolution-rules-plugin#22]
Libraries like Jackson have modules that release at difference cadences from the core libraries, either running behind, or ahead on patch releases making it impossible to align by highest version.

In the case of Jackson, everything seems to keep step, but modules that have seen patches that would be problematic for alignment are:

- http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.module%22%20AND%20a%3A%22jackson-module-kotlin%22
- http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.module%22%20AND%20a%3A%22jackson-module-scala_2.11%22

The idea is to support a regular expression pattern that determines how the version is compared for alignment.

**Comment by quidryan** [comment]
In the context of Jackson, org.codehaus.jackson should be mapped to com.fasterxml.jackson.

**Comment by DanielThomas** [comment]
They've got different packages `org/codehaus/jackson` vs `com/fasterxml/jackson`, so don't think there's anything we should do with them, other than perhaps have separate align rules for them.
