### ISSUE TITLE
Allow rules to override other rules.

### ISSUE THREAD

**Issue by noel-yap** [nebula-plugins/gradle-resolution-rules-plugin#43]
I would like to create an alignment rule between some internal libraries and `io.grpc` libraries. It doesn't make much sense to pollute the public alignment rule with cruft specific to our internal libraries. OTOH, currently, creating an internal rule will create non-determinism or conflicts with the public rule.

Ideally, I should be able to create the internal rule and have it tell the `gradle-resolution-rules-plugin` that it overrides the public rule.

**Comment by DanielThomas** [comment]
It'll be several weeks before we get to this, so in the meantime we'll need to keep conflicting rules public.

**Comment by DanielThomas** [comment]
In the next release.
