### ISSUE TITLE
Support a minimum version

### ISSUE THREAD

**Issue by quidryan** [nebula-plugins/gradle-resolution-rules-plugin#44]
It's common to have a minimum version that is acceptable. If a module has too low of a version the plugin could bring it up to the minimum.

**Comment by DanielThomas** [comment]
In 1.8.0.

**Comment by DanielThomas** [comment]
https://github.com/nebula-plugins/gradle-resolution-rules-plugin/wiki/Dependency-Rule-Types#minimum-version-rule
