### ISSUE TITLE
Reject rules deny access to first order dependency after all

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-resolution-rules-plugin#45]
We originally thought this was safe, but first orders can be denied.

**Comment by rpalcolea** [comment]
@OdysseusLives is this something that we still need to do ?

**Comment by OdysseusLives** [comment]
The [reject rule](https://github.com/nebula-plugins/gradle-resolution-rules-plugin/blob/v7.4.1/src/main/kotlin/nebula/plugin/resolutionrules/rules.kt#L163-L178) applies to both direct dependencies and transitives, with the idea that if you'd like this version to always be rejected, people cannot pull it in at all.

The way to avoid this is to exclude a particular rule entirely if that version is deliberately needed.

While it can cause a failure to resolve a dependency, when also used with a substitution rule, then this works out very well to remove that version from the graph and introduce a substituted version.

**Comment by rpalcolea** [comment]
IS it ok to close this?

**Comment by OdysseusLives** [comment]
I think that we can close this, in that I believe this "rejecting first orders" is a feature even if was unintentional at first.
