### ISSUE TITLE
Add support for bundled dependencies

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-resolution-rules-plugin#5]
Add support for bundling based on a group, or wildcard, so that dependencies in a given bundled are all aligned to the latest version in the graph.

**Comment by rspieldenner** [comment]
partially implemented in 1.1.4

**Comment by DanielThomas** [comment]
We need regex support for these too: for instance `com.amazonaws:aws-java-sdk-.*`
