### ISSUE TITLE
Provide exclusion rule

### ISSUE THREAD

**Issue by rbrindl** [nebula-plugins/gradle-resolution-rules-plugin#6]
I would volunteer to provide an exclusion rule if that makes sense to anyone except me.

Neither reject nor deny allow to just skip a dependency and remove it from the graph. The use case for this is to remove a certain (transitive) dependency that contains duplicate classes that are provided by another jar (or the jdk itself).

**Comment by rspieldenner** [comment]
We're open to pull requests.

**Comment by DanielThomas** [comment]
Yep, an 'exclude' rule type certainly seems reasonable.

**Comment by DanielThomas** [comment]
Will be released in 1.3.0.
