### ISSUE TITLE
Rules not applied to compileClasspath configuration

### ISSUE THREAD

**Issue by zerogvt** [nebula-plugins/gradle-resolution-rules-plugin#65]
Hi,
I'm trying to use the plugin in one of my projects and I noticed that while the rules are apllied to `compile` configuration, they are ignored when the dependencies for `compileClasspath` configuration are calculated.

E.g. for rule:
```
{
    "substitute": [
        {
            "module" : "com.fasterxml.jackson.core:jackson-databind:2.8.11",
            "with" : "com.fasterxml.jackson.core:jackson-databind:2.9.4",
        }
]
}
```

I get (dependency tree):
```
compile - Dependencies for source set 'main'.
...
+--- com.fasterxml.jackson.core:jackson-databind:2.8.11 -> 2.9.4
```

but

```
compileClasspath - Compile classpath for source set 'main'.
...
+--- com.fasterxml.jackson.core:jackson-databind:2.8.11
```

Not sure whether I'm missing something or this is a bug.
Thanks in advance.

**Comment by rpalcolea** [comment]
This should be working as of latest version.

Please give it a try and if it shows up again, feel free to re-open the issue
