### ISSUE TITLE
Deny rule with wild card is not supported

### ISSUE THREAD

**Issue by kamesh25** [nebula-plugins/gradle-resolution-rules-plugin#68]
I would like to deny builds with any example-common major minor 2.0 version as as example below, I see that currently deny rule only allows exact matched version in the module, Is there any way I can use wild card.

Thanks

{
  "deny": [
    {
      "module": "com.examplee:example-common:2.0.+",
      "reason": "this is bad version",
      "author": "Kamesh",
      "date": "2018-03-07"
    }
  ]
}

**Comment by DanielThomas** [comment]
Use substitutions instead - better fit for bad versions, they support ranges, and won’t fail the build:

https://github.com/nebula-plugins/gradle-resolution-rules-plugin/wiki/Dependency-Rule-Types#minimum-version-rule

Gradle’s new constraint support will also help with this kind of case.
